[tool.poetry]
name = "jthon"
<<<<<<< HEAD
version = "1.0.2"
=======
version = "1.0.3"
>>>>>>> 19872d1 (initial commit)
description = ""
authors = ["StroupBSlayen <29642143+stroupbslayen@users.noreply.github.com>", "ProbsJustin <jmksobieski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
